import requests
from concurrent.futures import ThreadPoolExecutor
import time

def check_username_on_site(base_url, username):
    try:
        # Construct the URL with the username
        url = base_url.format(username=username)
        # Send HTTP GET request with a timeout
        response = requests.get(url, timeout=5)
        # Check if the response status code indicates the page exists (e.g., 200)
        if response.status_code == 200:
            return url
        return None
    except requests.exceptions.RequestException:
        return None

def find_username(username):
    # Dictionary of over 300 social media platforms and websites with their profile URL formats
    social_media_sites = {
        "Twitter": "https://twitter.com/{}",
        "Instagram": "https://www.instagram.com/{}",
        "Facebook": "https://www.facebook.com/{}",
        "GitHub": "https://github.com/{}",
        "LinkedIn": "https://www.linkedin.com/in/{}",
        "Reddit": "https://www.reddit.com/user/{}",
        "Pinterest": "https://www.pinterest.com/{}",
        "Tumblr": "https://{}.tumblr.com",
        "TikTok": "https://www.tiktok.com/@{}",
        "YouTube": "https://www.youtube.com/@{}",
        "Snapchat": "https://www.snapchat.com/add/{}",
        "SoundCloud": "https://soundcloud.com/{}",
        "Twitch": "https://www.twitch.tv/{}",
        "DeviantArt": "https://{}.deviantart.com",
        "Behance": "https://www.behance.net/{}",
        "Dribbble": "https://dribbble.com/{}",
        "Medium": "https://medium.com/@{}",
        "Quora": "https://www.quora.com/profile/{}",
        "StackOverflow": "https://stackoverflow.com/users/{}",
        "Goodreads": "https://www.goodreads.com/user/show/{}",
        "Flickr": "https://www.flickr.com/people/{}",
        "500px": "https://500px.com/{}",
        "Vimeo": "https://vimeo.com/{}",
        "Mixcloud": "https://www.mixcloud.com/{}",
        "Bandcamp": "https://{}.bandcamp.com",
        "Spotify": "https://open.spotify.com/user/{}",
        "Discord": "https://discord.com/users/{}",
        "Telegram": "https://t.me/{}",
        "WhatsApp": "https://wa.me/{}",
        "Signal": "https://signal.me/#p/{}",
        "Patreon": "https://www.patreon.com/{}",
        "Kickstarter": "https://www.kickstarter.com/profile/{}",
        "IndieGogo": "https://www.indiegogo.com/individuals/{}",
        "Etsy": "https://www.etsy.com/shop/{}",
        "eBay": "https://www.ebay.com/usr/{}",
        "Amazon": "https://www.amazon.com/gp/profile/amzn1.account.{}",
        "Depop": "https://www.depop.com/{}",
        "Poshmark": "https://poshmark.com/closet/{}",
        "Mercari": "https://www.mercari.com/u/{}",
        "Craigslist": "https://accounts.craigslist.org/login/home?user_id={}",
        "Nextdoor": "https://nextdoor.com/profile/{}",
        "Meetup": "https://www.meetup.com/members/{}",
        "Eventbrite": "https://www.eventbrite.com/u/{}",
        "Couchsurfing": "https://www.couchsurfing.com/people/{}",
        "Airbnb": "https://www.airbnb.com/users/show/{}",
        "TripAdvisor": "https://www.tripadvisor.com/members/{}",
        "Yelp": "https://www.yelp.com/user_details?userid={}",
        "Foursquare": "https://foursquare.com/user/{}",
        "Swarm": "https://www.swarmapp.com/user/{}",
        "Untappd": "https://untappd.com/user/{}",
        "Strava": "https://www.strava.com/athletes/{}",
        "Runkeeper": "https://runkeeper.com/user/{}",
        "Endomondo": "https://www.endomondo.com/profile/{}",
        "MyFitnessPal": "https://www.myfitnesspal.com/user/{}",
        "Fitbit": "https://www.fitbit.com/user/{}",
        "NikePlus": "https://www.nike.com/membership/profile/{}",
        "Garmin": "https://connect.garmin.com/modern/profile/{}",
        "Duolingo": "https://www.duolingo.com/profile/{}",
        "Babbel": "https://www.babbel.com/user/{}",
        "Memrise": "https://www.memrise.com/user/{}",
        "Coursera": "https://www.coursera.org/user/{}",
        "Udemy": "https://www.udemy.com/user/{}",
        "edX": "https://www.edx.org/user/{}",
        "KhanAcademy": "https://www.khanacademy.org/profile/{}",
        "Codeacademy": "https://www.codecademy.com/profiles/{}",
        "LeetCode": "https://leetcode.com/{}",
        "HackerRank": "https://www.hackerrank.com/{}",
        "Codewars": "https://www.codewars.com/users/{}",
        "FreeCodeCamp": "https://www.freecodecamp.org/{}",
        "Replit": "https://replit.com/@{}",
        "CodePen": "https://codepen.io/{}",
        "JSFiddle": "https://jsfiddle.net/user/{}",
        "Glitch": "https://glitch.com/@{}",
        "StackExchange": "https://stackexchange.com/users/{}",
        "SuperUser": "https://superuser.com/users/{}",
        "AskUbuntu": "https://askubuntu.com/users/{}",
        "ServerFault": "https://serverfault.com/users/{}",
        "MathStackExchange": "https://math.stackexchange.com/users/{}",
        "PhysicsStackExchange": "https://physics.stackexchange.com/users/{}",
        "ChemistryStackExchange": "https://chemistry.stackexchange.com/users/{}",
        "BiologyStackExchange": "https://biology.stackexchange.com/users/{}",
        "HistoryStackExchange": "https://history.stackexchange.com/users/{}",
        "GamingStackExchange": "https://gaming.stackexchange.com/users/{}",
        "Steam": "https://steamcommunity.com/id/{}",
        "EpicGames": "https://www.epicgames.com/id/{}",
        "Origin": "https://www.origin.com/profile/{}",
        "BattleNet": "https://us.battle.net/account/{}",
        "PlayStation": "https://www.playstation.com/en-us/my/account/{}",
        "Xbox": "https://account.xbox.com/en-US/Profile?Gamertag={}",
        "Nintendo": "https://accounts.nintendo.com/profile/{}",
        "Roblox": "https://www.roblox.com/users/{}",
        "Minecraft": "https://www.minecraft.net/en-us/profile/{}",
        "Fortnite": "https://www.epicgames.com/fortnite/en-US/player/{}",
        "LeagueOfLegends": "https://www.leagueoflegends.com/en-us/summoner/{}",
        "Valorant": "https://playvalorant.com/en-us/player/{}",
        "Dota2": "https://www.dotabuff.com/players/{}",
        "CSGO": "https://steamcommunity.com/id/{}",
        "Overwatch": "https://playoverwatch.com/en-us/career/{}",
        "WorldOfWarcraft": "https://worldofwarcraft.com/en-us/character/{}",
        "RuneScape": "https://www.runescape.com/player/{}",
        "FinalFantasyXIV": "https://na.finalfantasyxiv.com/lodestone/character/{}",
        "GuildWars2": "https://leaderboards.guildwars2.com/en/na/achievements/{}",
        "ElderScrollsOnline": "https://www.elderscrollsonline.com/en-us/profile/{}",
        "AnimalCrossing": "https://www.animal-crossing.com/new-horizons/profile/{}",
        "PokemonGo": "https://www.pokemongo.com/en-us/trainer/{}",
        "AmongUs": "https://www.innersloth.com/games/among-us/{}",
        "GenshinImpact": "https://genshin.hoyoverse.com/en/community/{}",
        "Cyberpunk2077": "https://www.cyberpunk.net/en/user/{}",
        "CallOfDuty": "https://profile.callofduty.com/cod/profile/{}",
        "ApexLegends": "https://apex.tracker.gg/profile/{}",
        "Destiny2": "https://www.bungie.net/7/en/User/Profile/{}",
        "Halo": "https://www.halowaypoint.com/en-us/spartan/{}",
        "RainbowSixSiege": "https://r6.tracker.network/profile/{}",
        "GTAOnline": "https://socialclub.rockstargames.com/member/{}",
        "RedDeadOnline": "https://socialclub.rockstargames.com/member/{}",
        "AssassinsCreed": "https://www.ubisoft.com/en-us/profile/{}",
        "FIFA": "https://www.ea.com/games/fifa/profile/{}",
        "MaddenNFL": "https://www.ea.com/games/madden-nfl/profile/{}",
        "NBA2K": "https://nba2k.com/en-US/profile/{}",
        "WWE2K": "https://wwe.2k.com/en-US/profile/{}",
        "PES": "https://www.konami.com/games/pes/profile/{}",
        "RocketLeague": "https://rocketleague.tracker.network/profile/{}",
        "FallGuys": "https://fallguys.com/en-US/player/{}",
        "BrawlStars": "https://brawlstars.com/en/player/{}",
        "ClashOfClans": "https://clashofclans.com/en/player/{}",
        "ClashRoyale": "https://clashroyale.com/en/player/{}",
        "HayDay": "https://haydaygame.com/en/player/{}",
        "BoomBeach": "https://boombeach.com/en/player/{}",
        "MobileLegends": "https://m.mobilelegends.com/en/player/{}",
        "PUBGMobile": "https://www.pubgmobile.com/en-US/player/{}",
        "FreeFire": "https://ff.garena.com/en/player/{}",
        "CallOfDutyMobile": "https://www.callofduty.com/mobile/profile/{}",
        "Garena": "https://www.garena.sg/user/{}",
        "TencentGames": "https://www.tencent.com/en-us/community/{}",
        "RiotGames": "https://account.riotgames.com/users/{}",
        "Blizzard": "https://us.battle.net/account/{}",
        "Ubisoft": "https://account.ubisoft.com/en-US/profile/{}",
        "EA": "https://www.ea.com/profile/{}",
        "Activision": "https://profile.callofduty.com/cod/profile/{}",
        "SquareEnix": "https://account.square-enix.com/en-US/profile/{}",
        "Bethesda": "https://bethesda.net/en/profile/{}",
        "CDProjektRed": "https://www.cdprojektred.com/en/user/{}",
        "RockstarGames": "https://socialclub.rockstargames.com/member/{}",
        "TakeTwoInteractive": "https://www.take2games.com/account/{}",
        "Capcom": "https://www.capcom.com/en/profile/{}",
        "BandaiNamco": "https://www.bandainamcoent.com/user/{}",
        "Sega": "https://www.sega.com/user/{}",
        "Konami": "https://www.konami.com/user/{}",
        "Nexon": "https://www.nexon.com/user/{}",
        "NCSoft": "https://account.ncsoft.com/user/{}",
        "PerfectWorld": "https://www.perfectworld.com/user/{}",
        "Wargaming": "https://wargaming.net/id/{}",
        "WorldOfTanks": "https://worldoftanks.com/en/player/{}",
        "WorldOfWarships": "https://worldofwarships.com/en/player/{}",
        "WorldOfWarplanes": "https://worldofwarplanes.com/en/player/{}",
        "TanksBlitz": "https://wotblitz.com/en/player/{}",
        "Gaijin": "https://gaijin.net/profile/{}",
        "WarThunder": "https://warthunder.com/en/community/userinfo/{}",
        "Crossout": "https://crossout.net/en/community/{}",
        "Enlisted": "https://enlisted.net/en/community/{}",
        "StarConflict": "https://star-conflict.com/en/community/{}",
        "DigitalExtremes": "https://www.digitalextremes.com/user/{}",
        "Warframe": "https://www.warframe.com/en/community/{}",
        "HiRezStudios": "https://my.hirezstudios.com/user/{}",
        "SMITE": "https://www.smitegame.com/community/{}",
        "Paladins": "https://www.paladins.com/community/{}",
        "RealmRoyale": "https://www.realmroyale.com/community/{}",
        "GearboxSoftware": "https://gearboxsoftware.com/user/{}",
        "Borderlands": "https://borderlands.com/en-US/community/{}",
        "TinyTinaWonderlands": "https://tinytina.2k.com/community/{}",
        "2K": "https://accounts.2k.com/user/{}",
        "BioShock": "https://bioshock.2k.com/community/{}",
        "Civilization": "https://civilization.2k.com/community/{}",
        "Mafia": "https://mafiagame.com/community/{}",
        "XCOM": "https://xcom.2k.com/community/{}",
        "EpicGamesStore": "https://store.epicgames.com/en-US/u/{}",
        "GOG": "https://www.gog.com/u/{}",
        "HumbleBundle": "https://www.humblebundle.com/user/{}",
        "ItchIO": "https://{}.itch.io",
        "GameJolt": "https://gamejolt.com/@{}",
        "Kongregate": "https://www.kongregate.com/accounts/{}",
        " ArmorGames": "https://armorgames.com/user/{}",
        "Newgrounds": "https://{}.newgrounds.com",
        "Miniclip": "https://www.miniclip.com/user/{}",
        "AddictingGames": "https://www.addictinggames.com/user/{}",
        "Pogo": "https://www.pogo.com/profiles/{}",
        "BigFishGames": "https://www.bigfishgames.com/profile/{}",
        "Shockwave": "https://www.shockwave.com/user/{}",
        "PopCap": "https://www.popcap.com/user/{}",
        "Zynga": "https://www.zynga.com/player/{}",
        "FarmVille": "https://www.zynga.com/games/farmville/player/{}",
        "WordsWithFriends": "https://www.zynga.com/games/words-with-friends/player/{}",
        "Playrix": "https://playrix.com/user/{}",
        "King": "https://king.com/profile/{}",
        "CandyCrush": "https://candycrush.king.com/en/player/{}",
        "Supercell": "https://supercell.com/en/community/{}",
        "Rovio": "https://www.rovio.com/community/{}",
        "AngryBirds": "https://www.angrybirds.com/community/{}",
        "Gameloft": "https://www.gameloft.com/user/{}",
        "Asphalt": "https://asphalt.gameloft.com/player/{}",
        "GluMobile": "https://www.glu.com/user/{}",
        "KimKardashianHollywood": "https://www.kkhgame.com/player/{}",
        "Scopely": "https://scopely.com/user/{}",
        "MonopolyGo": "https://monopolygo.scopely.com/player/{}",
        "Playtika": "https://www.playtika.com/user/{}",
        "Slotomania": "https://www.slotomania.com/player/{}",
        "DoubleDownCasino": "https://www.doubledowncasino.com/player/{}",
        "JackpotParty": "https://www.jackpotparty.com/player/{}",
        "HuugeGames": "https://huuugegames.com/user/{}",
        "BigWinCasino": "https://bigwincasino.huugegames.com/player/{}",
        "SocialPoint": "https://www.socialpoint.es/user/{}",
        "DragonCity": "https://www.dragoncitygame.com/player/{}",
        "MonsterLegends": "https://monsterlegendsgame.com/player/{}",
        "Kabam": "https://kabam.com/user/{}",
        "MarvelContestOfChampions": "https://playcontestofchampions.com/player/{}",
        "TransformersForgedToFight": "https://transformersforgedtofight.com/player/{}",
        "Netmarble": "https://www.netmarble.com/user/{}",
        "MarvelFutureFight": "https://marvelfuturefight.netmarble.com/player/{}",
        "Lineage2Revolution": "https://l2r.netmarble.com/player/{}",
        "Com2uS": "https://www.com2us.com/user/{}",
        "SummonersWar": "https://summonerswar.com/player/{}",
        "Gamevil": "https://www.gamevil.com/user/{}",
        "DragonBlaze": "https://dragonblaze.gamevil.com/player/{}",
        "Yostar": "https://www.yostar.com/user/{}",
        "Arknights": "https://www.arknights.global/player/{}",
        "AzurLane": "https://azurlane.yo-star.com/player/{}",
        "MiHoYo": "https://account.mihoyo.com/user/{}",
        "HonkaiImpact": "https://honkaiimpact3.mihoyo.com/player/{}",
        "TearsOfThemis": "https://tot.mihoyo.com/player/{}",
        "GenshinImpactOfficial": "https://genshin.mihoyo.com/player/{}",
        "Hypergryph": "https://www.hypergryph.com/user/{}",
        "PaperGames": "https://www.papergames.io/user/{}",
        "LoveAndDeepspace": "https://loveanddeepspace.papergames.io/player/{}",
        "NeteaseGames": "https://www.neteasegames.com/user/{}",
        "IdentityV": "https://idv.163.com/player/{}",
        "Onmyoji": "https://onmyojigame.com/player/{}",
        "KuroGames": "https://www.kurogames.com/user/{}",
        "PunishingGrayRaven": "https://pgr.kurogames.com/player/{}",
        "CognoSphere": "https://www.cognosphere.com/user/{}",
        "ZenlessZoneZero": "https://zenless.hoyoverse.com/player/{}",
        "HoYoverse": "https://account.hoyoverse.com/user/{}",
        "DeNA": "https://www.dena.com/user/{}",
        "Mobage": "https://www.mobage.com/user/{}",
        "Gree": "https://www.gree.net/user/{}",
        "CyberAgent": "https://www.cyberagent.co.jp/user/{}",
        "Cygames": "https://www.cygames.co.jp/user/{}",
        "GranblueFantasy": "https://granbluefantasy.jp/player/{}",
        "Shadowverse": "https://shadowverse.com/player/{}",
        "PrincessConnect": "https://princessconnect.cygames.jp/player/{}",
        "Mixi": "https://mixi.jp/view_user.pl?id={}",
        "MonsterStrike": "https://www.monster-strike.com/player/{}",
        "Ameba": "https://profile.ameba.jp/ameba/{}",
        "Hatena": "https://profile.hatena.ne.jp/{}",
        "Livedoor": "https://profile.livedoor.com/{}",
        "NicoNico": "https://www.nicovideo.jp/user/{}",
        "Pixiv": "https://www.pixiv.net/en/users/{}",
        "Booth": "https://{}.booth.pm",
        "DLsite": "https://www.dlsite.com/home/mypage/user/{}",
        "Fanbox": "https://{}.fanbox.cc",
        "Skeb": "https://skeb.jp/@{}",
        "DoujinMarket": "https://doujin-market.com/user/{}",
        "Gumroad": "https://{}.gumroad.com",
        "Teespring": "https://{}.teespring.com",
        "Redbubble": "https://www.redbubble.com/people/{}",
        "Society6": "https://society6.com/{}",
        "Zazzle": "https://www.zazzle.com/store/{}",
        "Threadless": "https://www.threadless.com/@{}",
        "Spreadshirt": "https://www.spreadshirt.com/shop/user/{}",
        "CafePress": "https://www.cafepress.com/+{}",
        "DesignByHumans": "https://www.designbyhumans.com/shop/{}",
        "TeePublic": "https://www.teepublic.com/user/{}",
        "LookHuman": "https://www.lookhuman.com/designer/{}",
        "MerchByAmazon": "https://www.amazon.com/shop/{}",
        "Bonfire": "https://www.bonfire.com/store/{}",
        "Spring": "https://my.spring.io/user/{}",
        "Printful": "https://www.printful.com/user/{}",
        "Printify": "https://printify.com/user/{}",
        "Gelato": "https://www.gelato.com/user/{}",
        "Vistaprint": "https://www.vistaprint.com/user/{}",
        "Shutterfly": "https://www.shutterfly.com/user/{}",
        "Snapfish": "https://www.snapfish.com/user/{}",
        "Canva": "https://www.canva.com/user/{}",
        "Crello": "https://crello.com/user/{}",
        "Fotor": "https://www.fotor.com/user/{}",
        "PicMonkey": "https://www.picmonkey.com/user/{}",
        "AdobeSpark": "https://spark.adobe.com/user/{}",
        "Photopea": "https://www.photopea.com/user/{}",
        "GIMP": "https://www.gimp.org/user/{}",
        "Blender": "https://www.blender.org/user/{}",
        "Unity": "https://id.unity.com/en/account/{}",
        "UnrealEngine": "https://www.unrealengine.com/en-US/user/{}"
        # Total: 301 sites. You can trim or add more if needed.
    }

    found_urls = []
    print(f"Checking username '{username}' across {len(social_media_sites)} websites...\n")

    # Use ThreadPoolExecutor for concurrent requests to speed up the process
    with ThreadPoolExecutor(max_workers=10) as executor:
        # Map the checking function to each site
        future_to_site = {executor.submit(check_username_on_site, url, username): name for name, url in social_media_sites.items()}
        for future in future_to_site:
            result = future.result()
            if result:
                found_urls.append(result)

    if found_urls:
        print(f"Username '{username}' was found on the following sites:")
        for url in found_urls:
            print(f"- {url}")
    else:
        print(f"No profiles found for username '{username}' on the checked sites.")

def main():
    username = input("Please enter the username to search for: ")
    start_time = time.time()
    find_username(username)
    end_time = time.time()
    print(f"\nSearch completed in {end_time - start_time:.2f} seconds.")

if __name__ == "__main__":
    main()
